2022-05-20 09:35:25,537 Downloading and reading artifact
wandb: ERROR Project ivopdm/exercise_5 does not contain artifact: "preprocessed_data.csv:latest"
Traceback (most recent call last):
  File "/Users/ivopdm/.conda/envs/mlflow-2b1ad849cb5860f74406cc875a50bb09825a1a67/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/Users/ivopdm/.conda/envs/mlflow-2b1ad849cb5860f74406cc875a50bb09825a1a67/lib/python3.8/site-packages/wandb/apis/public.py", line 520, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/Users/ivopdm/.conda/envs/mlflow-2b1ad849cb5860f74406cc875a50bb09825a1a67/lib/python3.8/site-packages/wandb/apis/public.py", line 2583, in __init__
    self._load()
  File "/Users/ivopdm/.conda/envs/mlflow-2b1ad849cb5860f74406cc875a50bb09825a1a67/lib/python3.8/site-packages/wandb/apis/public.py", line 3097, in _load
    raise ValueError(
ValueError: Project ivopdm/exercise_5 does not contain artifact: "preprocessed_data.csv:latest"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 120, in <module>
    go(args)
  File "run.py", line 21, in go
    artifact = run.use_artifact(args.input_artifact)
  File "/Users/ivopdm/.conda/envs/mlflow-2b1ad849cb5860f74406cc875a50bb09825a1a67/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1957, in use_artifact
    artifact = public_api.artifact(type=type, name=name)
  File "/Users/ivopdm/.conda/envs/mlflow-2b1ad849cb5860f74406cc875a50bb09825a1a67/lib/python3.8/site-packages/wandb/apis/normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/Users/ivopdm/.conda/envs/mlflow-2b1ad849cb5860f74406cc875a50bb09825a1a67/lib/python3.8/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/Users/ivopdm/.conda/envs/mlflow-2b1ad849cb5860f74406cc875a50bb09825a1a67/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/Users/ivopdm/.conda/envs/mlflow-2b1ad849cb5860f74406cc875a50bb09825a1a67/lib/python3.8/site-packages/wandb/apis/public.py", line 520, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/Users/ivopdm/.conda/envs/mlflow-2b1ad849cb5860f74406cc875a50bb09825a1a67/lib/python3.8/site-packages/wandb/apis/public.py", line 2583, in __init__
    self._load()
  File "/Users/ivopdm/.conda/envs/mlflow-2b1ad849cb5860f74406cc875a50bb09825a1a67/lib/python3.8/site-packages/wandb/apis/public.py", line 3097, in _load
    raise ValueError(
wandb.errors.error.CommError: Project ivopdm/exercise_5 does not contain artifact: "preprocessed_data.csv:latest"
